# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  node: circleci/node@4.1
  heroku: circleci/heroku@0.0.10

workflows:
  test:
    jobs:
      - node/test:
          version: '14.17.4'
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git
        requires:
        - test
        filters:
            branches:
              only: main
